# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_for_postgres'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_for_postgres'

# These configurations specify where dbt should look for different types of files.
model-paths:
<<<<<<< Updated upstream
  - |
    {%- if target.name == "dev" -%} 
    models/sbic_models
    {%- endif -%}
=======
  - "models"
  
>>>>>>> Stashed changes

analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Specify the target directory for compiled SQL files.
target-path: "target"

# Specify directories to be removed by `dbt clean`.
clean-targets:
  - "target"
  - "dbt_packages"

# Configure models
models:
  sbic_models:  # Assuming your model group is named "sbic_models"
    # Remove unused configurations (if applicable)
    # example:  # Remove this line if not used

    enc_aadhar_information:
      # Existing configurations...
      database: "nithin"  # Replace with your target database name
      schema: "nivea"   # Replace with your target schema name

packages:
  - package: dbt-labs/dbt_utils
    version: ">=0.8.0"  # Specify the desired version here
