dbt_for_postgres:
  outputs:

    dev:
      type: postgres
      threads: 1
      host: 172.28.7.11 #"{{ env_var('postgres_host')}}"
      user: m2pappusr # "{{ env_var('postgres_user')}}"
      pass:  ykU_vP3+)YvI  #"{{ env_var('postgres_password')}}"
      dbname: indusind_reports #"{{ env_var('postgres_dbname')}}"
      schema: dw #"{{ env_var('postgres_schema')}}"
      port: 5665 # "{{ env_var('postgres_port' ) | int }}"

    prod:
     #type: postgres
      #threads: [1 or more]
      #host: [host]
      #port: [port]
      #user: [prod_username]
      #pass: [prod_password]
      #dbname: [dbname]
      #schema: [prod_schema]
      type: postgres
      threads: 1
      host: 172.28.7.11  #"{{ env_var('postgres_host')}}"
      user: m2pappusr # "{{ env_var('postgres_user')}}"
      pass:  ykU_vP3+)YvI #"{{ env_var('postgres_password')}}"
      dbname: indusind_reports #"{{ env_var('postgres_dbname')}}"
      schema: dw #"{{ env_var('postgres_schema')}}"
      port: 5665 # "{{ env_var('postgres_port' ) | int }}"
  target: dev